=== FRC4607/Scouting-App/src/common/config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "heading": {
      "type": "string"
    },
    "logo": {
      "type": "string"
    },
    "skipTeamSelection": {
      "type": "boolean"
    },
    "forceQualifiers": {
      "type": "boolean"
    },
    "pages": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/page"
      }
    }
  },
  "required": [
    "pages"
  ],
  "$defs": {
    "page": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "widgets": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/widget"
          }
        }
      },
      "required": [
        "name",
        "widgets"
      ]
    },
    "validationInequality": {
      "type": "object",
      "properties": {
        "comparison": {
          "type": "string",
          "enum": [
            "less",
            "lessOrEqual",
            "greater",
            "greaterOrEqual",
            "equal"
          ]
        },
        "value": {
          "type": "integer"
        }
      },
      "required": [
        "value"
      ]
    },
    "validationRange": {
      "type": "object",
      "properties": {
        "comparison": {
          "type": "string",
          "enum": [
            "inRange",
            "outOfRange"
          ]
        },
        "value": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      },
      "required": [
        "value"
      ]
    },
    "validation": {
      "type": "object",
      "properties": {
        "comparison": {
          "type": "string",
          "enum": [
            "less",
            "lessOrEqual",
            "greater",
            "greaterOrEqual",
            "equal",
            "inRange",
            "outOfRange"
          ]
        }
      },
      "required": [
        "comparison"
      ],
      "oneOf": [
        {
          "$ref": "#/$defs/validationInequality"
        },
        {
          "$ref": "#/$defs/validationRange"
        }
      ]
    },
    "widgetDropdown": {
      "type": "object",
      "properties": {
        "type": {
          "const": "dropdown"
        },
        "defaultOption": {
          "type": "boolean"
        },
        "options": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "options"
      ]
    },
    "widgetDropdownWithPictures": {
      "type": "object",
      "properties": {
        "type": {
          "const": "dropdownwithpictures"
        },
        "defaultOption": {
          "type": "boolean"
        },
        "options": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "files": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "options",
        "files"
      ]
    },
    "widgetHeading": {
      "type": "object",
      "properties": {
        "type": {
          "const": "heading"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetLabel": {
      "type": "object",
      "properties": {
        "type": {
          "const": "label"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetText": {
      "type": "object",
      "properties": {
        "type": {
          "const": "text"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetNumber": {
      "type": "object",
      "properties": {
        "type": {
          "const": "number"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetCheckbox": {
      "type": "object",
      "properties": {
        "type": {
          "const": "checkbox"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetMultiCheckbox": {
      "type": "object",
      "properties": {
        "type": {
          "const": "multicheckbox"
        },
        "options": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "options"
      ]
    },
    "widgetPicture": {
      "type": "object",
      "properties": {
        "type": {
          "const": "picture"
        },
        "file": {
          "type": "string"
        },
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        }
      },
      "required": [
        "file"
      ]
    },
    "widgetPositions": {
      "type": "object",
      "properties": {
        "type": {
          "const": "positions"
        },
        "file": {
          "type": "string"
        },
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        },
        "allowMultiple": {
          "type": "boolean"
        },
        "selectRadius": {
          "type": "integer"
        },
        "selectColor": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "file"
      ]
    },
    "widgetRadio": {
      "type": "object",
      "properties": {
        "type": {
          "const": "radio"
        },
        "options": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "default": {
          "type": "integer"
        }
      },
      "required": [
        "name",
        "options"
      ]
    },
    "widgetSpacer": {
      "type": "object",
      "properties": {
        "type": {
          "const": "spacer"
        },
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        }
      }
    },
    "widgetSpinbox": {
      "type": "object",
      "properties": {
        "type": {
          "const": "spinbox"
        },
        "min": {
          "type": "integer"
        },
        "max": {
          "type": "integer"
        },
        "allowKeyboardInput": {
          "type": "boolean"
        },
        "buttonColor": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetStopwatch": {
      "type": "object",
      "properties": {
        "type": {
          "const": "stopwatch"
        },
        "startLabel": {
          "type": "string"
        },
        "lapLabel": {
          "type": "string"
        },
        "stopLabel": {
          "type": "string"
        },
        "maxLaps": {
          "type": "integer"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetAverageStopwatch": {
      "type": "object",
      "properties": {
        "type": {
          "const": "averagestopwatch"
        },
        "startLabel": {
          "type": "string"
        },
        "undoLabel": {
          "type": "string"
        },
        "stopLabel": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetTextarea": {
      "type": "object",
      "properties": {
        "type": {
          "const": "textarea"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetToggleGrid": {
      "type": "object",
      "properties": {
        "type": {
          "const": "togglegrid"
        },
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        },
        "colors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "rowColors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "colColors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "width",
        "height",
        "colors"
      ]
    },
    "widgetPictureUpload": {
      "type": "object",
      "properties": {
        "type": {
          "const": "pictureupload"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetTeamRanking": {
      "type": "object",
      "properties": {
        "type": {
          "const": "teamranking"
        },
        "alliance": {
          "enum": ["red", "blue"]
        }
      },
      "required": [
        "alliance"
      ]
    },
    "widgetCheckboxGrid": {
      "type": "object",
      "properties": {
        "type": {
          "const": "checkboxgrid"
        },
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        },
        "leftOffset": {
          "type": "integer"
        },
        "rightOffset": {
          "type": "integer"
        },
        "topOffset": {
          "type": "integer"
        },
        "bottomOffset": {
          "type": "integer"
        }
      },
      "required": [
        "name"
      ]
    },
    "widget": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "dropdown",
            "dropdownwithpictures",
            "heading",
            "label",
            "text",
            "number",
            "checkbox",
            "multicheckbox",
            "picture",
            "positions",
            "radio",
            "spacer",
            "spinbox",
            "stopwatch",
            "averagestopwatch",
            "textarea",
            "togglegrid",
            "pictureupload",
            "checkboxgrid",
            "teamranking"
          ]
        },
        "prefix": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "displayName": {
          "type": "string"
        },
        "align": {
          "type": "string",
          "enum": [
            "left",
            "center",
            "right"
          ]
        },
        "noLabel": {
          "type": "boolean"
        },
        "row": {
          "type": "integer"
        },
        "col": {
          "type": "integer"
        },
        "rowspan": {
          "type": "integer"
        },
        "colspan": {
          "type": "integer"
        },
        "labelColspan": {
          "type": "integer"
        },
        "validation": {
          "$ref": "#/$defs/validation"
        }
      },
      "required": [
        "type"
      ],
      "oneOf": [
        {
          "$ref": "#/$defs/widgetDropdown"
        },
        {
          "$ref": "#/$defs/widgetDropdownWithPictures"
        },
        {
          "$ref": "#/$defs/widgetHeading"
        },
        {
          "$ref": "#/$defs/widgetLabel"
        },
        {
          "$ref": "#/$defs/widgetText"
        },
        {
          "$ref": "#/$defs/widgetNumber"
        },
        {
          "$ref": "#/$defs/widgetCheckbox"
        },
        {
          "$ref": "#/$defs/widgetMultiCheckbox"
        },
        {
          "$ref": "#/$defs/widgetPicture"
        },
        {
          "$ref": "#/$defs/widgetPositions"
        },
        {
          "$ref": "#/$defs/widgetRadio"
        },
        {
          "$ref": "#/$defs/widgetSpacer"
        },
        {
          "$ref": "#/$defs/widgetSpinbox"
        },
        {
          "$ref": "#/$defs/widgetStopwatch"
        },
        {
          "$ref": "#/$defs/widgetAverageStopwatch"
        },
        {
          "$ref": "#/$defs/widgetTextarea"
        },
        {
          "$ref": "#/$defs/widgetToggleGrid"
        },
        {
          "$ref": "#/$defs/widgetPictureUpload"
        },
        {
          "$ref": "#/$defs/widgetCheckboxGrid"
        },
        {
          "$ref": "#/$defs/widgetTeamRanking"
        }
      ]
    }
  }
}

=== FRC4607/Scouting-App/public/assets/config-ranking.json
{
    "heading": "Crescendo - 2024 (Team Ranking)",
    "logo": "logo.png",
    "skipTeamSelection": true,
    "pages": [
        {
            "name": "Ranking",
            "widgets": [
                {
                    "displayName": "Match Number",
                    "name": "match",
                    "type": "number",
                    "validation": {
                        "comparison": "greaterOrEqual",
                        "value": 1
                    }
                },
                {
                    "name": "Note: It's OK to give teams the same rank!",
                    "type": "label",
                    "col": 2,
                    "colspan": 2,
                    "labelColspan": 2
                },
                {
                    "displayName": "Red Alliance Ranking",
                    "name": "red",
                    "type": "teamranking",
                    "alliance": "red"
                },
                {
                    "displayName": "Blue Alliance Ranking",
                    "name": "blue",
                    "type": "teamranking",
                    "alliance": "blue"
                }
            ]
        }
    ]
}

=== FRC4607/Scouting-App/public/assets/config-pits.json
{
  "heading": "Crescendo - 2024 (Pit Scouting)",
  "logo": "logo.png",
  "skipTeamSelection": true,
  "pages": [
    {
      "name": "Robot",
      "widgets": [
        {
          "displayName": "Scouter Name",
          "name": "scouter_name",
          "type": "text"
        },
        {
          "displayName": "Team Number",
          "name": "team_number",
          "type": "number"
        },
        {
          "displayName": "Length",
          "name": "length",
          "type": "number"
        },
        {
          "displayName": "Width",
          "name": "width",
          "type": "number"
        },
        {
          "displayName": "Weight",
          "name": "weight",
          "type": "number"
        },
        {
          "displayName": "Drivetrain Type",
          "name": "dt_type",
          "type": "dropdown",
          "options": [
            "Tank Drive",
            "Mecanum",
            "Swerve",
            "Other"
          ]
        },
        {
          "displayName": "Swerve Motor Type",
          "name": "swerve_motor",
          "type": "dropdown",
          "options": [
            "Neo",
            "Falcon",
            "Cim"
          ]
        },
        {
          "displayName": "Swerve Type",
          "name": "swerve_type",
          "type": "dropdown",
          "options": [
            "No swerve",
            "L1",
            "L2",
            "L3",
            "L4",
            "Neo",
            "Falcon",
            "Custom"
          ]
        }
      ]
    },
    {
      "name": "Gameplay and Programming",
      "widgets": [
        {
          "displayName": "Cycle Time",
          "name": "cycle_time",
          "type": "number"
        },
        {
          "displayName": "Can Pick Up",
          "name": "can_pickup",
          "type": "multicheckbox",
          "options": [
            "Ground",
            "Source"
          ]
        },
        {
          "displayName": "Can Score In",
          "name": "scoring_locations",
          "type": "multicheckbox",
          "options": [
            "Speaker",
            "Amp",
            "Trap"
          ]
        }
      ]
    },
    {
      "name": "Processes",
      "widgets": [
        {
          "displayName": "Number of Batteries",
          "name": "num_batt",
          "type": "number",
          "min": 1
        },
        {
          "displayName": "Battery Maintenance",
          "name": "does_batt_maint",
          "type": "checkbox"
        },
        {
          "displayName": "Battery Maintenance_text",
          "name": "batt_maint_txt",
          "noLabel": true,
          "type": "text",
          "col": 2
        },
        {
          "displayName": "Batteries Get Tested",
          "name": "batt_testing",
          "type": "checkbox"
        },
        {
          "displayName": "Main Battery Brand",
          "name": "batt_brand",
          "type": "dropdown",
          "options": [
            "MK",
            "Interstate",
            "Duracell",
            "Mighty Max",
            "Other (comments)"
          ]
        },
        {
          "displayName": "Our batteries needed during playoffs",
          "name": "batt_needed",
          "type": "checkbox"
        },
        {
          "displayName": "Pit Checklist",
          "name": "pit_checklist",
          "type": "checkbox"
        },
        {
          "displayName": "Does Scouting",
          "name": "does_scouting",
          "type": "checkbox"
        },
        {
          "displayName": "Willing to trade scouting data",
          "name": "trade_scouting_data",
          "type": "checkbox"
        }
      ]
    },
    {
      "name": "Pictures and Comments",
      "widgets": [
        {
          "name": "Note: You can upload multiple pictures/videos for each section!",
          "type": "label",
          "colspan": 2,
          "labelColspan": 2
        },
        {
          "displayName": "space",
          "type": "spacer"
        },
        {
          "displayName": "Battery Storage and Charging Area",
          "name": "batt_storchrg",
          "type": "pictureupload"
        },
        {
          "displayName": "Battery Location On Robot",
          "name": "batt_loc",
          "type": "pictureupload"
        },
        {
          "displayName": "Battery Connector Close Up",
          "name": "batt_con",
          "type": "pictureupload"
        },
        {
          "displayName": "Main Power Switch Location",
          "name": "powersw_loc",
          "type": "pictureupload"
        },
        {
          "displayName": "Robot Close Ups and Features",
          "name": "misc_pics",
          "type": "pictureupload"
        },
        {
          "displayName": "space",
          "type": "spacer"
        },
        {
          "displayName": "Scoring Methods",
          "name": "scoring_method",
          "type": "multicheckbox",
          "options": [
            "Manual",
            "Auto"
          ]
        },
        {
          "displayName": "Preferred Pickup Location",
          "name": "preferred_pickup",
          "type": "dropdown",
          "options": [
            "Ground",
            "Source"
          ],
          "defaultOption": true
        },
        {
          "displayName": "Comments",
          "name": "comments",
          "type": "textarea",
          "colspan": 2
        }
      ]
    }
  ]
}
